# Site settings
title: LiuBang
SEOTitle: 刘邦的博客 | 刘邦
header-img: img/home-bg.jpg
email: it.liubang@gmail.com
description: "后端开发 | 这里是 @LiuBang 刘邦 的个人博客，与你一起发现更大的世界。"
keyword: "刘邦,Liubang,BangLua,php,c,Java,go服务端开发,后端开发,web开发"
url: "https://iliubang.github.io"
baseurl: ""



# SNS settings
RSS: false
weibo_username:     AdolphLiu001
# zhihu_username:     liubang
github_username:    iliubang
twitter_username:  iliubang
facebook_username:  100011819431893
# linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
# anchorjs: true



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]

# Disqus settings
disqus_username: liubang

highlighter: rouge
# highlighter: pygments
markdown: kramdown
kramdown:
  input: GFM


# Analytics settings
# Baidu Analytics
ba_track_id: d9426b8b196111b4af56f34a6e45d32a
# Google Analytics
# ga_track_id: 'UA-80711026-1'            # Format: UA-xxxxxx-xx
# ga_domain: auto



# Sidebar settings
sidebar: true
sidebar-about-description: "whether you are an antelope or a lion,you ought to dash forward without hesitation when the sun rise"
sidebar-avatar: /img/lb.jpg



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
          title: "liubang",
          href: "https://iliubang.github.io/"
    },
    {
          title: "李成龙",
          href: "https://lichenglong.pw/"
    }
]
